name: sonda
description: An app is to use sounds as a way to relax, focus, or simply transport oneself to the tropical paradise that is Puerto Rico.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_riverpod: ^2.0.2
  hive_flutter: ^1.1.0
  lottie: ^2.2.0
  flutter_native_splash: ^2.2.1
  riverpod: ^2.0.2
  animate_do: ^3.0.2
  flutter_svg: ^1.1.0
  im_stepper: ^1.0.1+1
  flutter_staggered_animations: ^1.0.0
  html_unescape: ^2.0.0
  flutter_easyloading: ^3.0.5
  circular_countdown_timer: ^0.2.1
  awesome_dialog: ^3.0.2
  url_launcher: ^6.1.3
  audioplayers: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  firebase_core: ^2.4.1
  audioplayers_darwin: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: AtHaussStd
      fonts:
        - asset: assets/fonts/AtHaussStd-Retina.otf
          weight: 400
        - asset: assets/fonts/AtHaussStd-Semibold.otf
          weight: 600
